const translations = {
    en: {
        nav_tech: "Our Tech",
        nav_portal: "Patient Portal",
        nav_resources: "Tremor Resources",
        hero_title: "Reclaiming Stillness Through Innovation",
        hero_subtext: "Advanced neuro-haptic solutions for managing hand tremors. Experience the future of stability.",
        hero_cta: "BUY NOW",
        tech_title: "The Future of Steadiness",
        tech_desc: "Our flagship adaptive gyro-stabilization technology counteracts involuntary movements in real-time.",
        research_title: "Research First",
        research_desc: "Backed by years of clinical research and developed by a diverse team of neuroscientists and engineers.",
        survey_title: "Patient Intake Form",
        label_name: "Patient Name",
        placeholder_name: "Enter your full name",
        label_date: "Date",
        q1: "1. When did you first notice the tremor, and has it changed over time?",
        placeholder_q1: "Describe your experience...",
        q2: "2. Does the shaking occur when your hands are completely relaxed (at rest), or does it start/worsen when you try to perform an action?",
        q2_opt1: "Mostly when hands are relaxed (at rest)",
        q2_opt2: "Mostly when I use my hands (reaching, holding, writing)",
        q2_opt3: "Both",
        q3: "3. Does the tremor affect both hands?",
        q3_opt1: "Yes, both hands equally",
        q3_opt2: "Yes, but one is worse than the other",
        q3_opt3: "No, only one hand",
        q4: "4. Do you have any blood relatives who also suffer from hand tremors?",
        q4_opt1: "Yes",
        q4_opt2: "No",
        q4_opt3: "I don't know",
        q5: "5. Have you noticed if the tremor temporarily decreases after consuming a small amount of alcohol?",
        q5_opt1: "Yes, it improves",
        q5_opt2: "No, no change",
        q5_opt3: "I do not drink alcohol",
        q6: "6. Which daily activities are most difficult for you? (Check all that apply)",
        q6_opt1: "Eating (using a spoon/fork)",
        q6_opt2: "Drinking from a cup",
        q6_opt3: "Writing",
        q6_opt4: "Using a phone/keyboard",
        q6_opt5: "Buttoning clothes/tying shoelaces",
        q7: "7. Do you have an implanted pacemaker, cardiac defibrillator (ICD), or any other active electronic device in your body?",
        q7_opt1: "Yes",
        q7_opt2: "No",
        q8: "8. Do you suffer from epilepsy, or have you ever had seizures in the past?",
        q8_opt1: "Yes",
        q8_opt2: "No",
        q9: "9. Do you have any metal implants (plates, pins, shrapnel) in your wrist or forearm area?",
        q9_opt1: "Yes",
        q9_opt2: "No",
        q10: "10. Do you have any open wounds, skin inflammation, eczema, or recent scars in the wrist area?",
        q10_opt1: "Yes",
        q10_opt2: "No",
        q11: "11. Are you currently pregnant?",
        q11_opt1: "Yes",
        q11_opt2: "No",
        q11_opt3: "N/A (Male)",
        q12: "12. Do you have reduced sensitivity (numbness or lack of feeling) in the skin of your hands?",
        q12_opt1: "Yes",
        q12_opt2: "No",
        q13: "13. Where do you feel the tremor most intensely?",
        q13_opt1: "Fingers and Wrist",
        q13_opt2: "Whole arm and Shoulder",
        q13_opt3: "Head or Voice",
        q14: "14. Do you tolerate the sensation of slight vibration or \"tingling\" on your skin well?",
        q14_opt1: "Yes",
        q14_opt2: "No / I have sensitive skin",
        q15: "15. Will you be able to put on and tighten a bracelet on your wrist by yourself?",
        q15_opt1: "Yes",
        q15_opt2: "No, I will need assistance",
        submit_btn: "Submit Survey",
        resources_title: "UNDERSTANDING HAND TREMORS",
        tremor_types: "Types of Tremors",
        tremor_list1: "Essential Tremor",
        tremor_list2: "Parkinsonian Tremor",
        tremor_list3: "Dystonic Tremor",
        science_title: "The Science Behind the Shake",
        science_list1: "Neurological pathways",
        science_list2: "Signal disruption",
        science_list3: "Motor cortex activity",
        daily_title: "Managing Daily Life",
        daily_list1: "Adaptive tools",
        daily_list2: "Stress management",
        daily_list3: "Physical therapy",
        footer_privacy: "Privacy Policy",
        footer_contact: "Contact Us",
        newsletter_placeholder: "Stay updated...",
        newsletter_btn: "Subscribe",
        copyright: "&copy; 2025 Futura Innovation Technologies"
    },
    bg: {
        nav_tech: "Нашите Технологии",
        nav_portal: "Пациентски Портал",
        nav_resources: "Ресурси за Тремор",
        hero_title: "Възвръщане на Спокойствието чрез Иновации",
        hero_subtext: "Разширени невро-хаптични решения за управление на тремор на ръцете. Изпитайте бъдещето на стабилността.",
        hero_cta: "КУПИ СЕГА",
        tech_title: "Бъдещето на Стабилността",
        tech_desc: "Нашата водеща технология за адаптивна жиро-стабилизация противодейства на неволните движения в реално време.",
        research_title: "Изследванията на Първо Място",
        research_desc: "Подкрепени от години клинични изследвания и разработени от разнообразен екип от невролози и инженери.",
        survey_title: "Формуляр за Прием на Пациенти",
        label_name: "Име на Пациента",
        placeholder_name: "Въведете пълното си име",
        label_date: "Дата",
        q1: "1. Кога за първи път забелязахте тремора и променил ли се е с времето?",
        placeholder_q1: "Опишете своя опит...",
        q2: "2. Треперенето появява ли се, когато ръцете ви са напълно отпуснати (в покой), или започва/се влошава, когато се опитвате да извършите действие?",
        q2_opt1: "Повече, когато ръцете са отпуснати (в покой)",
        q2_opt2: "Повече, когато използвам ръцете си (посягане, държане, писане)",
        q2_opt3: "И двете",
        q3: "3. Треморът засяга ли и двете ръце?",
        q3_opt1: "Да, и двете ръце еднакво",
        q3_opt2: "Да, но едната е по-зле от другата",
        q3_opt3: "Не, само едната ръка",
        q4: "4. Имате ли кръвни роднини, които също страдат от тремор на ръцете?",
        q4_opt1: "Да",
        q4_opt2: "Не",
        q4_opt3: "Не знам",
        q5: "5. Забелязали ли сте дали треморът временно намалява след консумация на малко количество алкохол?",
        q5_opt1: "Да, подобрява се",
        q5_opt2: "Не, няма промяна",
        q5_opt3: "Не употребявам алкохол",
        q6: "6. Кои ежедневни дейности са най-трудни за вас? (Отбележете всички, които важат)",
        q6_opt1: "Хранене (използване на лъжица/вилица)",
        q6_opt2: "Пиене от чаша",
        q6_opt3: "Писане",
        q6_opt4: "Използване на телефон/клавиатура",
        q6_opt5: "Закопчаване на дрехи/вързване на връзки",
        q7: "7. Имате ли имплантиран пейсмейкър, сърдечен дефибрилатор (ICD) или друго активно електронно устройство в тялото си?",
        q7_opt1: "Да",
        q7_opt2: "Не",
        q8: "8. Страдате ли от епилепсия или имали ли сте някога припадъци в миналото?",
        q8_opt1: "Да",
        q8_opt2: "Не",
        q9: "9. Имате ли метални импланти (плаки, пирони, шрапнели) в областта на китката или предмишницата?",
        q9_opt1: "Да",
        q9_opt2: "Не",
        q10: "10. Имате ли отворени рани, възпаление на кожата, екзема или скорошни белези в областта на китката?",
        q10_opt1: "Да",
        q10_opt2: "Не",
        q11: "11. Бременна ли сте в момента?",
        q11_opt1: "Да",
        q11_opt2: "Не",
        q11_opt3: "N/A (Мъж)",
        q12: "12. Имате ли намалена чувствителност (изтръпване или липса на усещане) в кожата на ръцете си?",
        q12_opt1: "Да",
        q12_opt2: "Не",
        q13: "13. Къде усещате тремора най-силно?",
        q13_opt1: "Пръсти и Китка",
        q13_opt2: "Цялата ръка и Рамо",
        q13_opt3: "Глава или Глас",
        q14: "14. Понасяте ли добре усещането за лека вибрация или \"мравучкане\" по кожата си?",
        q14_opt1: "Да",
        q14_opt2: "Не / Имам чувствителна кожа",
        q15: "15. Ще можете ли сами да поставите и затегнете гривна на китката си?",
        q15_opt1: "Да",
        q15_opt2: "Не, ще имам нужда от помощ",
        submit_btn: "Изпрати Анкетата",
        resources_title: "РАЗБИРАНЕ НА ТРЕМОРА НА РЪЦЕТЕ",
        tremor_types: "Видове Тремори",
        tremor_list1: "Есенциален Тремор",
        tremor_list2: "Паркинсонов Тремор",
        tremor_list3: "Дистоничен Тремор",
        science_title: "Науката Зад Треперенето",
        science_list1: "Неврологични пътища",
        science_list2: "Нарушение на сигнала",
        science_list3: "Активност на моторния кортекс",
        daily_title: "Управление на Ежедневието",
        daily_list1: "Адаптивни инструменти",
        daily_list2: "Управление на стреса",
        daily_list3: "Физиотерапия",
        footer_privacy: "Политика за Поверителност",
        footer_contact: "Контакти",
        newsletter_placeholder: "Бъдете информирани...",
        newsletter_btn: "Абонирай се",
        copyright: "&copy; 2025 Futura Innovation Technologies"
    }
};

function changeLanguage(lang) {
    document.querySelectorAll('[data-i18n]').forEach(element => {
        const key = element.getAttribute('data-i18n');
        if (translations[lang] && translations[lang][key]) {
            if (element.tagName === 'INPUT' || element.tagName === 'TEXTAREA') {
                element.placeholder = translations[lang][key];
            } else {
                element.innerHTML = translations[lang][key];
            }
        }
    });

    // Update active state of language buttons
    document.querySelectorAll('.lang-btn').forEach(btn => {
        btn.classList.remove('active');
        if (btn.getAttribute('onclick').includes(lang)) {
            btn.classList.add('active');
        }
    });
}
